# vim ft=yaml
# travis-ci.org definition for NICEMAN build
#language: python
sudo: required
#dist: precise

os:
  - osx

matrix:
  include:
    - os: osx
      osx_image: xcode9
      language: objective-c
      env: TRAVIS_PYTHON_VERSION=2.7
    - os: osx
      osx_image: xcode9
      language: objective-c
      env: TRAVIS_PYTHON_VERSION=3.4

env:
  # to overcome problem with system-wide installed boto on travis
  # see https://github.com/travis-ci/travis-ci/issues/5246
  - BOTO_CONFIG=/tmp/nowhere

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        source osx_install.sh
      else
        bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
        travis_retry sudo apt-get update -qq
        git config --global user.email "test@travis.land"
        git config --global user.name "Travis Almighty"
        docker run -d -p 49000:22 rastasheep/ubuntu-sshd:14.04
      fi

install:
  # - tools/ci/build_install_apt  # Removed dependency on python-apt!
  - cd ..; pip install -q codecov; cd -
  - pip install --upgrade pip
  # needed by html5lib
  - pip install --upgrade 'setuptools>=18.5'
  - pip install -r requirements-devel.txt
  # So we could test under sudo -E with PATH pointing to installed location
  - sudo sed -i -e 's/^Defaults.*secure_path.*$//' /etc/sudoers

script:
  # Verify that setup.py build doesn't puke
  - python setup.py build
  - if [ ! -z "$NICEMAN_TESTS_NONETWORK" ]; then sudo route add -net 0.0.0.0 netmask 0.0.0.0 dev lo; fi
  # - $NOSE_WRAPPER `which nosetests` -s -v --with-doctest --doctest-tests --with-cov --cover-package niceman --logging-level=INFO
  - coverage run `which py.test` niceman
  - if [ ! -z "$NICEMAN_TESTS_NONETWORK" ]; then sudo route del -net 0.0.0.0 netmask 0.0.0.0 dev lo; fi
  # Generate documentation and run doctests
  - PYTHONPATH=$PWD make -C docs html doctest

after_success:
  - codecov

# makes it only more difficult to comprehend the failing output.  Enable only when necessary
# for a particular debugging
#after_failure:
#  - if [ ! -z "$NICEMAN_TESTS_NONETWORK" ]; then sudo route add -net 0.0.0.0 netmask 0.0.0.0 dev lo; fi
#  - NICEMAN_LOGLEVEL=DEBUG $NOSE_WRAPPER `which nosetests` -s -v --with-doctest --doctest-tests --with-cov --cover-package niceman --logging-level=DEBUG
#  - if [ ! -z "$NICEMAN_TESTS_NONETWORK" ]; then sudo route del -net 0.0.0.0 netmask 0.0.0.0 dev lo; fi
